### ISSUE TITLE
TimePicker is not shown on landscape orientation

### ISSUE THREAD

**Issue by albertovelazmoliner** [vikramkakkar/SublimePicker#31]
TimePicker is not shown on landscape orientation, and I'm getting this log:

D/android.support.v7.widget.GridLayout: horizontal constraints: x1-x0>=503, x2-x1>=816, x2-x0<=1176 are inconsistent; permanently removing: x2-x0<=1176.  
D/android.support.v7.widget.GridLayout: vertical constraints: y1-y0>=0, y2-y1>=720, y3-y2>=192, y3-y0<=909 are inconsistent; permanently removing: y3-y0<=909.

It's happening in Nexus 4 (Android 5.1), Nexus 5 (Android 5.0) and Samsung S5 (Android 5.1) with your original project in github.

![device-2016-05-18-090117](https://cloud.githubusercontent.com/assets/1174318/15350063/6f9beca4-1cd7-11e6-8c22-d413f30e28c4.png)

**Comment by vikramkakkar** [comment]
This is odd since the sample app was tested on both nex 4 & 5. I will look into what the log messages are saying, but I already have an alternate layout coded up (thanks to #27) - one that does not use `GridLayout`. I believe that clipping on smaller screens (~< 300dp) will be more acceptable than the screenshot above.

**Comment by albertovelazmoliner** [comment]
Yes, you're right, I didn't see the issue #27 . Thanks

**Comment by albertovelazmoliner** [comment]
It's done
